export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/MojoCodeInc/Mojo-Code",
	GITHUB_DISCUSSIONS: "https://github.com/MojoCodeInc/Mojo-Code/discussions",
	DISCORD: "https://discord.gg/Mojocode",
	REDDIT: "https://reddit.com/r/MojoCode",
	X: "https://x.com/Mojo_code",
	LINKEDIN: "https://www.linkedin.com/company/Mojo-code",
	TIKTOK: "https://www.tiktok.com/@Mojo.code",
	BLUESKY: "https://bsky.app/profile/Mojocode.bsky.social",
	YOUTUBE: "https://www.youtube.com/@MojoCodeYT",
	DOCUMENTATION: "https://docs.Mojocode.com",
	CAREERS: "https://careers.Mojocode.com",
	ISSUES: "https://github.com/MojoCodeInc/Mojo-Code/issues",
	FEATURE_REQUESTS: "https://github.com/MojoCodeInc/Mojo-Code/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/MojoCodeInc/Mojo-Code/discussions",
	CHANGELOG: "https://github.com/MojoCodeInc/Mojo-Code/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/MojoCodeInc/Mojo-Code/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.Mojocode.com/community",
	TUTORIALS: "https://docs.Mojocode.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=MojoVeterinaryInc.Mojo-cline",
	SECURITY: "https://trust.Mojocode.com",
	EVALS: "https://Mojocode.com/evals",
	BLOG: "https://blog.Mojocode.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@MojoCodeYT/podcasts",
	FAQ: "https://Mojocode.com/#faq",
	TESTIMONIALS: "https://Mojocode.com/#testimonials",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
